# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpcs.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nrpcs.proto\"g\n\x12RequestVoteRequest\x12\x14\n\x0c\x63\x61ndidate_id\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x05\x12\x15\n\rlast_log_term\x18\x04 \x01(\x05\"N\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\x12\x13\n\x0blease_timer\x18\x03 \x01(\x01\"%\n\x05\x45ntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06update\x18\x02 \x03(\t\"\xad\x01\n\x14\x41ppendEntriesRequest\x12\x12\n\nleaderTerm\x18\x01 \x01(\x05\x12\x10\n\x08leaderId\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x17\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x06.Entry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\x12\x15\n\rleaseDuration\x18\x07 \x01(\x01\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"C\n\x12ServeClientRequest\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x10\n\x08variable\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"N\n\x13ServeClientResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x12\n\nis_success\x18\x03 \x01(\x08\x32\xba\x01\n\x04Raft\x12\x38\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\x12>\n\rAppendEntries\x12\x15.AppendEntriesRequest\x1a\x16.AppendEntriesResponse\x12\x38\n\x0bServeClient\x12\x13.ServeClientRequest\x1a\x14.ServeClientResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rpcs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=14
  _globals['_REQUESTVOTEREQUEST']._serialized_end=117
  _globals['_REQUESTVOTERESPONSE']._serialized_start=119
  _globals['_REQUESTVOTERESPONSE']._serialized_end=197
  _globals['_ENTRY']._serialized_start=199
  _globals['_ENTRY']._serialized_end=236
  _globals['_APPENDENTRIESREQUEST']._serialized_start=239
  _globals['_APPENDENTRIESREQUEST']._serialized_end=412
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=414
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=468
  _globals['_SERVECLIENTREQUEST']._serialized_start=470
  _globals['_SERVECLIENTREQUEST']._serialized_end=537
  _globals['_SERVECLIENTRESPONSE']._serialized_start=539
  _globals['_SERVECLIENTRESPONSE']._serialized_end=617
  _globals['_RAFT']._serialized_start=620
  _globals['_RAFT']._serialized_end=806
# @@protoc_insertion_point(module_scope)
